<?php

namespace rvilbrandt\gamebook\Loader;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-04 at 09:45:51.
 */
class SerializeSessionTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var SerializeSession
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SerializeSession;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers rvilbrandt\gamebook\Loader\SerializeSession::load
     */
    public function testLoad() {
        
        $object = new \stdClass();
        $object->test = 1705;
        
        $_SESSION['test'] = serialize($object);
        
        $this->assertEquals($object, $this->object->load("test"));
    }

}
