<?php

namespace rvilbrandt\gamebook\Saver;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-04 at 09:47:43.
 */
class SerializeSessionTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var SerializeSession
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SerializeSession;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers rvilbrandt\gamebook\Saver\SerializeSession::write
     */
    public function testWrite() {
        $this->assertNull($this->object->write("test", new \stdClass()));
    }

}
