<?php

namespace rvilbrandt\gamebook\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-26 at 14:15:02.
 */
class GamebookTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Gamebook
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Gamebook;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers rvilbrandt\gamebook\Model\Gamebook::fetchScene
     */
    public function testFetchScene() {
        $this->object->setFromObject(json_decode(file_get_contents(__DIR__ . "/../../data/gamebook_valid.json")));
        $this->assertContains("Welcome to this great adventure", $this->object->fetchScene("beginning")->contents[0]->text);
    }

    /**
     * @covers rvilbrandt\gamebook\Model\Gamebook::setFromArray
     */
    public function testSetFromArray() {
        $this->object->setFromObject(json_decode(file_get_contents(__DIR__ . "/../../data/gamebook_valid.json")));
    }

}
