<?php

namespace rvilbrandt\gamebook\Model\Gamebook;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-29 at 07:55:59.
 */
class ConditionsTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Conditions
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Conditions;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers rvilbrandt\gamebook\Model\Gamebook\Conditions::setFromArray
     */
    public function testSetFromArray() {
        $this->object->setFromObject(json_decode(file_get_contents(__DIR__ . "/../../../data/conditions_valid.json")));
        
        $this->assertEquals("Hodor", $this->object->states->eq['name']);
        $this->assertEquals(1, $this->object->states->gt['test']);
        $this->assertContains("key", $this->object->inventory->has);
    }

}
