<?php

namespace rvilbrandt\gamebook\Model\Gamebook;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-26 at 13:57:37.
 */
class SceneTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Scene
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Scene;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers rvilbrandt\gamebook\Model\Gamebook\Scene::setFromObject
     */
    public function testSetFromObject() {
        $this->object->setFromObject(json_decode(file_get_contents(__DIR__ . "/../../../data/scene_valid.json")));

        $this->assertContains("key", $this->object->options[1]->conditions->inventory->hasNot);
        $this->assertContains("key", $this->object->options[2]->conditions->inventory->has);
        $this->assertEquals(1, $this->object->options[3]->conditions->states->eq['door_3_opened']);
    }

    /**
     * @covers rvilbrandt\gamebook\Model\Gamebook\Scene::setFromArray
     * @expectedException rvilbrandt\gamebook\Model\MissingAttributeException
     */
    public function testSetFromArrayIncompleteJson() {
        $this->object->setFromObject(json_decode(file_get_contents(__DIR__ . "/../../../data/object_incomplete.json")));
    }
    
}
